version: '3'                                                              

services:
  master:
    image: redis
    ports:
      - 6379:6379
  slave:
    image: redis
    command: redis-server --slaveof master 6379
  sentinel:
    image: redis-sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000

